version: '3.8'

services:
  tests:
    build:
      context: .
      dockerfile: Dockerfile.tests
  mssqldatabase: 
    build:
      context: ./Data
      dockerfile: Dockerfile.mssqldatabase 
    container_name: tapper_db
    hostname: tapper_infra_tests 
    restart: unless-stopped
    environment:
      SA_PASSWORD: "PaSSw0rd123!"
      ACCEPT_EULA: "Y"
    ports:
      - "5434:1433" 
    volumes:
      - mssqldata:/var/opt/mssql   
volumes:
  mssqldata:     